const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILED = "LOGIN_FAILED";
const VERIFICATION_REQUEST = "VERIFY_TOKEN";
const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
const VERIFICATION_FAILED = "VERIFICATION_FAILED";
const LOGOUT = 'LOGOUT';

export {
 LOGIN_REQUEST,
 LOGIN_SUCCESS,
 LOGIN_FAILED,
 VERIFICATION_REQUEST,
 VERIFICATION_SUCCESS,
 VERIFICATION_FAILED,
 LOGOUT,
};
