export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const CHECK_USERNAME = 'CHECK_USERNAME';
export const VALID_USERNAME = 'VALID_USERNAME';
export const INVALID_USERNAME = 'INVALID USERNAME';